
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class frameprincipal extends javax.swing.JFrame {

    Dato4[] listaDato=new Dato4[1];
    
    /**
     * Creates new form frameprincipal
     */
    public frameprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bttingresar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtcontra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        Bttingresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Bttingresar.setText("ingresar");
        Bttingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttingresarActionPerformed(evt);
            }
        });
        jPanel1.add(Bttingresar);
        Bttingresar.setBounds(200, 300, 130, 40);

        txtnombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        jPanel1.add(txtnombre);
        txtnombre.setBounds(80, 80, 190, 30);

        txtcontra.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        jPanel1.add(txtcontra);
        txtcontra.setBounds(80, 170, 190, 30);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 3, 18)); // NOI18N
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 60, 70, 20);

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 3, 18)); // NOI18N
        jLabel2.setText("Contrasena");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 150, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttingresarActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i <listaDato.length; i++) {
            if(listaDato[i]==null){
                Dato4 datos=new Dato4(txtnombre.getText(),txtcontra.getText());
                listaDato[i]=datos;
                break;
            }
        }

       
        for (int i = 0; i < listaDato.length; i++) {
            if (listaDato[i]!=null){
            System.out.println("Nombre"+listaDato[i].nombre+",Contrasena"+listaDato[i].contrasena);
           
            } 
        }
        int cui=201903763;
        for (int i = 0; i < listaDato.length; i++) {
          int valor=Integer.valueOf(listaDato[i].contrasena);  
          if(cui==valor){
             JOptionPane.showMessageDialog(null, " Hola bienvenido "+listaDato[i].nombre+" su contraseña es  "+valor);
          }else{
            JOptionPane.showMessageDialog(null, "EL Nombre o contraseña son incorectas");
        }
        }
    }//GEN-LAST:event_BttingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
